### ISSUE TITLE
COMP Error

### ISSUE THREAD

**Issue by hdoupe** [PSLmodels/Tax-Brain#71]
- sim: https://compmodels.org/PSLmodels/Tax-Brain/41832/, https://compmodels.org/PSLmodels/Tax-Brain/41833/

- inputs:
```json
{
    "policy": {
        "STD": [
            {
                "MARS": "single",
                "year": 2020,
                "value": 0.0
            },
            {
                "MARS": "mjoint",
                "year": 2020,
                "value": 0.0
            },
            {
                "MARS": "mseparate",
                "year": 2020,
                "value": 0.0
            },
            {
                "MARS": "headhh",
                "year": 2020,
                "value": 0.0
            },
            {
                "MARS": "widow",
                "year": 2020,
                "value": 0.0
            }
        ],
        "ID_c": [
            {
                "MARS": "single",
                "year": 2020,
                "value": 0.0
            },
            {
                "MARS": "mjoint",
                "year": 2020,
                "value": 0.0
            },
            {
                "MARS": "mseparate",
                "year": 2020,
                "value": 0.0
            },
            {
                "MARS": "headhh",
                "year": 2020,
                "value": 0.0
            },
            {
                "MARS": "widow",
                "year": 2020,
                "value": 0.0
            }
        ],
        "CTC_c": [
            {
                "year": 2020,
                "value": 1500.0
            }
        ],
        "II_em": [
            {
                "year": 2020,
                "value": 0.0
            }
        ],
        "ODC_c": [
            {
                "year": 2020,
                "value": 1500.0
            }
        ],
        "ACTC_c": [
            {
                "year": 2020,
                "value": 0.0
            }
        ],
        "CDCC_c": [
            {
                "year": 2020,
                "value": 0.0
            }
        ],
        "CTC_ps": [
            {
                "MARS": "single",
                "year": 2020,
                "value": 225000.0
            },
            {
                "MARS": "mjoint",
                "year": 2020,
                "value": 450000.0
            },
            {
                "MARS": "mseparate",
                "year": 2020,
                "value": 225000.0
            },
            {
                "MARS": "headhh",
                "year": 2020,
                "value": 250000.0
            },
            {
                "MARS": "widow",
                "year": 2020,
                "value": 450000.0
            }
        ],
        "II_rt1": [
            {
                "year": 2020,
                "value": 0.15
            }
        ],
        "II_rt2": [
            {
                "year": 2020,
                "value": 0.15
            }
        ],
        "II_rt3": [
            {
                "year": 2020,
                "value": 0.15
            }
        ],
        "II_rt4": [
            {
                "year": 2020,
                "value": 0.25
            }
        ],
        "II_rt5": [
            {
                "year": 2020,
                "value": 0.25
            }
        ],
        "II_rt6": [
            {
                "year": 2020,
                "value": 0.28
            }
        ],
        "II_rt7": [
            {
                "year": 2020,
                "value": 0.35
            }
        ],
        "UBI_21": [
            {
                "year": 2020,
                "value": 2375.0
            }
        ],
        "AMT_rt1": [
            {
                "year": 2020,
                "value": 0.0
            }
        ],
        "AMT_rt2": [
            {
                "year": 2020,
                "value": 0.0
            }
        ],
        "CTC_prt": [
            {
                "year": 2020,
                "value": 0.0125
            }
        ],
        "II_brk3": [
            {
                "MARS": "single",
                "year": 2020,
                "value": 62500.0
            },
            {
                "MARS": "mjoint",
                "year": 2020,
                "value": 125000.0
            },
            {
                "MARS": "mseparate",
                "year": 2020,
                "value": 62500.0
            },
            {
                "MARS": "headhh",
                "year": 2020,
                "value": 87500.0
            },
            {
                "MARS": "widow",
                "year": 2020,
                "value": 125000.0
            }
        ],
        "II_brk5": [
            {
                "MARS": "single",
                "year": 2020,
                "value": 250000.0
            },
            {
                "MARS": "mjoint",
                "year": 2020,
                "value": 500000.0
            },
            {
                "MARS": "mseparate",
                "year": 2020,
                "value": 250000.0
            },
            {
                "MARS": "headhh",
                "year": 2020,
                "value": 350000.0
            },
            {
                "MARS": "widow",
                "year": 2020,
                "value": 500000.0
            }
        ],
        "II_brk6": [
            {
                "MARS": "single",
                "year": 2020,
                "value": 625000.0
            },
            {
                "MARS": "mjoint",
                "year": 2020,
                "value": 1250000.0
            },
            {
                "MARS": "mseparate",
                "year": 2020,
                "value": 625000.0
            },
            {
                "MARS": "headhh",
                "year": 2020,
                "value": 750000.0
            },
            {
                "MARS": "widow",
                "year": 2020,
                "value": 1250000.0
            }
        ],
        "STD_Aged": [
            {
                "MARS": "single",
                "year": 2020,
                "value": 0.0
            },
            {
                "MARS": "mjoint",
                "year": 2020,
                "value": 0.0
            },
            {
                "MARS": "mseparate",
                "year": 2020,
                "value": 0.0
            },
            {
                "MARS": "headhh",
                "year": 2020,
                "value": 0.0
            },
            {
                "MARS": "widow",
                "year": 2020,
                "value": 0.0
            }
        ],
        "UBI_1820": [
            {
                "year": 2020,
                "value": 1875.0
            }
        ],
        "CG_nodiff": [
            {
                "year": 2020,
                "value": true
            }
        ],
        "II_credit": [
            {
                "MARS": "single",
                "year": 2020,
                "value": 2500.0
            },
            {
                "MARS": "mjoint",
                "year": 2020,
                "value": 5000.0
            },
            {
                "MARS": "mseparate",
                "year": 2020,
                "value": 2500.0
            },
            {
                "MARS": "headhh",
                "year": 2020,
                "value": 3000.0
            },
            {
                "MARS": "widow",
                "year": 2020,
                "value": 5000.0
            }
        ],
        "CPI_offset": [
            {
                "year": 2020,
                "value": -0.001875
            }
        ],
        "CR_SchR_hc": [
            {
                "year": 2020,
                "value": 1.0,
                "data_source": "PUF"
            }
        ],
        "PT_qbid_rt": [
            {
                "year": 2020,
                "value": 0.0
            }
        ],
        "II_credit_nr": [
            {
                "MARS": "single",
                "year": 2020,
                "value": 3750.0
            },
            {
                "MARS": "mjoint",
                "year": 2020,
                "value": 7500.0
            },
            {
                "MARS": "mseparate",
                "year": 2020,
                "value": 3750.0
            },
            {
                "MARS": "headhh",
                "year": 2020,
                "value": 5250.0
            },
            {
                "MARS": "widow",
                "year": 2020,
                "value": 7500.0
            }
        ],
        "ALD_Tuition_hc": [
            {
                "year": 2020,
                "value": 1.0,
                "data_source": "PUF"
            }
        ],
        "CTC_c_checkbox": [
            {
                "value": true
            }
        ],
        "ODC_c_checkbox": [
            {
                "value": true
            }
        ],
        "CR_Education_hc": [
            {
                "year": 2020,
                "value": 1.0,
                "data_source": "PUF"
            }
        ],
        "CTC_ps_checkbox": [
            {
                "value": true
            }
        ],
        "II_credit_nr_ps": [
            {
                "MARS": "single",
                "year": 2020,
                "value": 225000.0
            },
            {
                "MARS": "mjoint",
                "year": 2020,
                "value": 450000.0
            },
            {
                "MARS": "mseparate",
                "year": 2020,
                "value": 225000.0
            },
            {
                "MARS": "headhh",
                "year": 2020,
                "value": 250000.0
            },
            {
                "MARS": "widow",
                "year": 2020,
                "value": 450000.0
            }
        ],
        "CR_MinimumTax_hc": [
            {
                "year": 2020,
                "value": 1.0,
                "data_source": "PUF"
            }
        ],
        "II_credit_nr_prt": [
            {
                "year": 2020,
                "value": 0.025
            }
        ],
        "ALD_AlimonyPaid_hc": [
            {
                "year": 2020,
                "value": 1.0,
                "data_source": "PUF"
            }
        ],
        "ALD_StudentLoan_hc": [
            {
                "year": 2020,
                "value": 1.0
            }
        ],
        "CR_OtherCredits_hc": [
            {
                "year": 2020,
                "value": 1.0,
                "data_source": "PUF"
            }
        ],
        "CTC_c_under5_bonus": [
            {
                "year": 2020,
                "value": 1000.0
            }
        ],
        "ALD_HSADeduction_hc": [
            {
                "year": 2020,
                "value": 1.0,
                "data_source": "PUF"
            }
        ],
        "ALD_BusinessLosses_c": [
            {
                "MARS": "single",
                "year": 2020,
                "value": 50000.0
            },
            {
                "MARS": "mjoint",
                "year": 2020,
                "value": 100000.0
            },
            {
                "MARS": "mseparate",
                "year": 2020,
                "value": 50000.0
            },
            {
                "MARS": "headhh",
                "year": 2020,
                "value": 50000.0
            },
            {
                "MARS": "widow",
                "year": 2020,
                "value": 100000.0
            }
        ],
        "ALD_EarlyWithdraw_hc": [
            {
                "year": 2020,
                "value": 1.0,
                "data_source": "PUF"
            }
        ],
        "CR_AmOppRefundable_hc": [
            {
                "year": 2020,
                "value": 1.0,
                "data_source": "PUF"
            }
        ],
        "CR_GeneralBusiness_hc": [
            {
                "year": 2020,
                "value": 1.0,
                "data_source": "PUF"
            }
        ],
        "PT_EligibleRate_active": [
            {
                "year": 2020,
                "value": 0.0
            }
        ],
        "ALD_EducatorExpenses_hc": [
            {
                "year": 2020,
                "value": 1.0,
                "data_source": "PUF"
            }
        ],
        "CR_ResidentialEnergy_hc": [
            {
                "year": 2020,
                "value": 1.0,
                "data_source": "PUF"
            }
        ],
        "CR_RetirementSavings_hc": [
            {
                "year": 2020,
                "value": 1.0,
                "data_source": "PUF"
            }
        ],
        "CR_AmOppNonRefundable_hc": [
            {
                "year": 2020,
                "value": 1.0,
                "data_source": "PUF"
            }
        ],
        "ALD_DomesticProduction_hc": [
            {
                "year": 2020,
                "value": 1.0
            }
        ],
        "CTC_c_under5_bonus_checkbox": [
            {
                "value": true
            }
        ]
    },
    "behavior": {}
}
```

- traceback:

```
Traceback (most recent call last):
  File "/home/distributed/api/celery_app/__init__.py", line 71, in f
    outputs = func(*args, **kwargs)
  File "/home/distributed/api/celery_app/pslmodels_taxbrain_tasks.py", line 30, in sim
    return compconfig.run_model(meta_param_dict, adjustment)
  File "/opt/conda/lib/python3.7/site-packages/compconfig/functions.py", line 126, in run_model
    policy_mods = convert_adj(adjustment["policy"], meta_params.year.tolist())
  File "/opt/conda/lib/python3.7/site-packages/compconfig/helpers.py", line 170, in convert_adj
    pol.implement_reform(new_adj, raise_errors=False)
  File "/opt/conda/lib/python3.7/site-packages/taxcalc/policy.py", line 128, in implement_reform
    self._update(reform, print_warnings, raise_errors)
  File "/opt/conda/lib/python3.7/site-packages/taxcalc/parameters.py", line 335, in _update
    known_years = self._apply_cpi_offset_in_revision(revision)
  File "/opt/conda/lib/python3.7/site-packages/taxcalc/parameters.py", line 850, in _apply_cpi_offset_in_revision
    if self._vals[name]['indexed']:
KeyError: '_CTC_c-indexed'

```

**Comment by andersonfrailey** [comment]
This issue has been logged in the Tax-Calculator [repo](https://github.com/PSLmodels/Tax-Calculator/issues/2363) along with a [PR](https://github.com/PSLmodels/Tax-Calculator/pull/2364) to fix the bug.

**Comment by hdoupe** [comment]
Great, thanks @andersonfrailey!

**Comment by andersonfrailey** [comment]
Now that Tax-Calculator 2.5.0 has been released this should be resolved. Closing.
