### ISSUE TITLE
Compute Studio Error

### ISSUE THREAD

**Issue by hdoupe** [PSLmodels/Tax-Brain#86]
- links:
  - https://compute.studio/PSLmodels/Tax-Brain/42911/
  - https://compute.studio/PSLmodels/Tax-Brain/42912/
  - https://compute.studio/PSLmodels/Tax-Brain/4293/
  - https://compute.studio/PSLmodels/Tax-Brain/43003/
  - https://compute.studio/PSLmodels/Tax-Brain/43004/

- representative traceback:

```
          
Traceback (most recent call last):
  File "/home/distributed/api/celery_app/__init__.py", line 75, in f
    outputs = func(*args, **kwargs)
  File "/home/distributed/api/celery_app/pslmodels_taxbrain_tasks.py", line 49, in sim
    return compconfig.run_model(meta_param_dict, adjustment)
  File "/opt/conda/lib/python3.7/site-packages/compconfig/functions.py", line 169, in run_model
    tb.run()
  File "/opt/conda/lib/python3.7/site-packages/taxbrain/taxbrain.py", line 106, in run
    base_calc, reform_calc = self._make_calculators()
  File "/opt/conda/lib/python3.7/site-packages/taxbrain/taxbrain.py", line 383, in _make_calculators
    policy.implement_reform(self.params['policy'])
  File "/opt/conda/lib/python3.7/site-packages/taxcalc/policy.py", line 128, in implement_reform
    self._update(reform, print_warnings, raise_errors)
  File "/opt/conda/lib/python3.7/site-packages/taxcalc/parameters.py", line 351, in _update
    raise ValueError('\n' + self.parameter_errors)
ValueError: 
ERROR: 2020 II_brk5[single] value 443358.89 > max value 437039.0 for II_brk6[single]
ERROR: 2021 II_brk5[single] value 453689.15 > max value 437039.0 for II_brk6[single]
ERROR: 2022 II_brk5[single] value 464078.63 > max value 437039.0 for II_brk6[single]
ERROR: 2023 II_brk5[single] value 474659.62 > max value 437039.0 for II_brk6[single]
ERROR: 2023 II_brk5[headhh] value 474659.62 > max value 464354.0 for II_brk6[headhh]
ERROR: 2024 II_brk5[single] value 485149.6 > max value 437039.0 for II_brk6[single]
ERROR: 2024 II_brk5[headhh] value 485149.6 > max value 464354.0 for II_brk6[headhh]
ERROR: 2025 II_brk5[single] value 495386.26 > max value 437039.0 for II_brk6[single]
ERROR: 2025 II_brk5[mjoint] value 495386.26 > max value 491668.0 for II_brk6[mjoint]
ERROR: 2025 II_brk5[mseparate] value 247692.57 > max value 245834.0 for II_brk6[mseparate]
ERROR: 2025 II_brk5[headhh] value 495386.26 > max value 464354.0 for II_brk6[headhh]
ERROR: 2025 II_brk5[widow] value 495386.26 > max value 491668.0 for II_brk6[widow]
ERROR: 2026 II_brk5[single] value 505739.83 > max value 437039.0 for II_brk6[single]
ERROR: 2026 II_brk5[mjoint] value 505739.83 > max value 491668.0 for II_brk6[mjoint]
ERROR: 2026 II_brk5[mseparate] value 252869.34 > max value 245834.0 for II_brk6[mseparate]
ERROR: 2026 II_brk5[headhh] value 505739.83 > max value 464354.0 for II_brk6[headhh]
ERROR: 2026 II_brk5[widow] value 505739.83 > max value 491668.0 for II_brk6[widow]
ERROR: 2027 II_brk5[single] value 516410.94 > max value 437039.0 for II_brk6[single]
ERROR: 2027 II_brk5[mjoint] value 516410.94 > max value 491668.0 for II_brk6[mjoint]
ERROR: 2027 II_brk5[mseparate] value 258204.88 > max value 245834.0 for II_brk6[mseparate]
ERROR: 2027 II_brk5[headhh] value 516410.94 > max value 464354.0 for II_brk6[headhh]
ERROR: 2027 II_brk5[widow] value 516410.94 > max value 491668.0 for II_brk6[widow]
ERROR: 2028 II_brk5[single] value 527152.29 > max value 437039.0 for II_brk6[single]
ERROR: 2028 II_brk5[mjoint] value 527152.29 > max value 491668.0 for II_brk6[mjoint]
ERROR: 2028 II_brk5[mseparate] value 263575.54 > max value 245834.0 for II_brk6[mseparate]
ERROR: 2028 II_brk5[headhh] value 527152.29 > max value 464354.0 for II_brk6[headhh]
ERROR: 2028 II_brk5[widow] value 527152.29 > max value 491668.0 for II_brk6[widow]
ERROR: 2029 II_brk5[single] value 538222.49 > max value 437039.0 for II_brk6[single]
ERROR: 2029 II_brk5[mjoint] value 538222.49 > max value 491668.0 for II_brk6[mjoint]
ERROR: 2029 II_brk5[mseparate] value 269110.63 > max value 245834.0 for II_brk6[mseparate]
ERROR: 2029 II_brk5[headhh] value 538222.49 > max value 464354.0 for II_brk6[headhh]
ERROR: 2029 II_brk5[widow] value 538222.49 > max value 491668.0 for II_brk6[widow]
ERROR: 2020 II_brk6[single] value 437039.0 < min value 443358.89 for II_brk5[single]
ERROR: 2021 II_brk6[single] value 437039.0 < min value 453689.15 for II_brk5[single]
ERROR: 2022 II_brk6[single] value 437039.0 < min value 464078.63 for II_brk5[single]
ERROR: 2023 II_brk6[single] value 437039.0 < min value 474659.62 for II_brk5[single]
ERROR: 2023 II_brk6[headhh] value 464354.0 < min value 474659.62 for II_brk5[headhh]
ERROR: 2024 II_brk6[single] value 437039.0 < min value 485149.6 for II_brk5[single]
ERROR: 2024 II_brk6[headhh] value 464354.0 < min value 485149.6 for II_brk5[headhh]
ERROR: 2025 II_brk6[single] value 437039.0 < min value 495386.26 for II_brk5[single]
ERROR: 2025 II_brk6[mjoint] value 491668.0 < min value 495386.26 for II_brk5[mjoint]
ERROR: 2025 II_brk6[mseparate] value 245834.0 < min value 247692.57 for II_brk5[mseparate]
ERROR: 2025 II_brk6[headhh] value 464354.0 < min value 495386.26 for II_brk5[headhh]
ERROR: 2025 II_brk6[widow] value 491668.0 < min value 495386.26 for II_brk5[widow]
ERROR: 2026 II_brk6[single] value 437039.0 < min value 505739.83 for II_brk5[single]
ERROR: 2026 II_brk6[mjoint] value 491668.0 < min value 505739.83 for II_brk5[mjoint]
ERROR: 2026 II_brk6[mseparate] value 245834.0 < min value 252869.34 for II_brk5[mseparate]
ERROR: 2026 II_brk6[headhh] value 464354.0 < min value 505739.83 for II_brk5[headhh]
ERROR: 2026 II_brk6[widow] value 491668.0 < min value 505739.83 for II_brk5[widow]
ERROR: 2027 II_brk6[single] value 437039.0 < min value 516410.94 for II_brk5[single]
ERROR: 2027 II_brk6[mjoint] value 491668.0 < min value 516410.94 for II_brk5[mjoint]
ERROR: 2027 II_brk6[mseparate] value 245834.0 < min value 258204.88 for II_brk5[mseparate]
ERROR: 2027 II_brk6[headhh] value 464354.0 < min value 516410.94 for II_brk5[headhh]
ERROR: 2027 II_brk6[widow] value 491668.0 < min value 516410.94 for II_brk5[widow]
ERROR: 2028 II_brk6[single] value 437039.0 < min value 527152.29 for II_brk5[single]
ERROR: 2028 II_brk6[mjoint] value 491668.0 < min value 527152.29 for II_brk5[mjoint]
ERROR: 2028 II_brk6[mseparate] value 245834.0 < min value 263575.54 for II_brk5[mseparate]
ERROR: 2028 II_brk6[headhh] value 464354.0 < min value 527152.29 for II_brk5[headhh]
ERROR: 2028 II_brk6[widow] value 491668.0 < min value 527152.29 for II_brk5[widow]
ERROR: 2029 II_brk6[single] value 437039.0 < min value 538222.49 for II_brk5[single]
ERROR: 2029 II_brk6[mjoint] value 491668.0 < min value 538222.49 for II_brk5[mjoint]
ERROR: 2029 II_brk6[mseparate] value 245834.0 < min value 269110.63 for II_brk5[mseparate]
ERROR: 2029 II_brk6[headhh] value 464354.0 < min value 538222.49 for II_brk5[headhh]
ERROR: 2029 II_brk6[widow] value 491668.0 < min value 538222.49 for II_brk5[widow]

```

inputs: 
```json
{
    "meta_parameters": {
        "year": 2019,
        "data_source": "PUF",
        "use_full_sample": true
    },
    "adjustment": {
        "behavior": {},
        "policy": {
            "PT_rt7": [
                {
                    "year": 2019,
                    "value": 0.396
                }
            ],
            "PT_brk6": [
                {
                    "MARS": "mjoint",
                    "year": 2019,
                    "value": 491668
                },
                {
                    "MARS": "single",
                    "year": 2019,
                    "value": 437039
                },
                {
                    "MARS": "widow",
                    "year": 2019,
                    "value": 491668
                },
                {
                    "MARS": "headhh",
                    "year": 2019,
                    "value": 464354
                },
                {
                    "MARS": "mseparate",
                    "year": 2019,
                    "value": 245834
                }
            ],
            "PT_brk5": [
                {
                    "MARS": "mjoint",
                    "year": 2019,
                    "value": 435263
                },
                {
                    "MARS": "single",
                    "year": 2019,
                    "value": 435263
                },
                {
                    "MARS": "widow",
                    "year": 2019,
                    "value": 435263
                },
                {
                    "MARS": "headhh",
                    "year": 2019,
                    "value": 435263
                },
                {
                    "MARS": "mseparate",
                    "year": 2019,
                    "value": 217631
                }
            ],
            "PT_rt5": [
                {
                    "year": 2019,
                    "value": 0.33
                }
            ],
            "PT_brk4": [
                {
                    "MARS": "mjoint",
                    "year": 2019,
                    "value": 243745
                },
                {
                    "MARS": "single",
                    "year": 2019,
                    "value": 200187
                },
                {
                    "MARS": "widow",
                    "year": 2019,
                    "value": 243745
                },
                {
                    "MARS": "headhh",
                    "year": 2019,
                    "value": 221966
                },
                {
                    "MARS": "mseparate",
                    "year": 2019,
                    "value": 121873
                }
            ],
            "PT_rt4": [
                {
                    "year": 2019,
                    "value": 0.28
                }
            ],
            "PT_brk3": [
                {
                    "MARS": "mjoint",
                    "year": 2019,
                    "value": 159920
                },
                {
                    "MARS": "single",
                    "year": 2019,
                    "value": 95994
                },
                {
                    "MARS": "widow",
                    "year": 2019,
                    "value": 159920
                },
                {
                    "MARS": "headhh",
                    "year": 2019,
                    "value": 137045
                },
                {
                    "MARS": "mseparate",
                    "year": 2019,
                    "value": 79960
                }
            ],
            "PT_rt3": [
                {
                    "year": 2019,
                    "value": 0.25
                }
            ],
            "PT_rt2": [
                {
                    "year": 2019,
                    "value": 0.15
                }
            ],
            "II_rt7": [
                {
                    "year": 2019,
                    "value": 0.396
                }
            ],
            "II_brk6_checkbox": [
                {
                    "value": false
                }
            ],
            "II_brk6": [
                {
                    "MARS": "mjoint",
                    "year": 2019,
                    "value": 491668
                },
                {
                    "MARS": "single",
                    "year": 2019,
                    "value": 437039
                },
                {
                    "MARS": "widow",
                    "year": 2019,
                    "value": 491668
                },
                {
                    "MARS": "headhh",
                    "year": 2019,
                    "value": 464354
                },
                {
                    "MARS": "mseparate",
                    "year": 2019,
                    "value": 245834
                }
            ],
            "II_rt6": [
                {
                    "year": 2019,
                    "value": 0.35
                }
            ],
            "II_brk5": [
                {
                    "MARS": "mjoint",
                    "year": 2019,
                    "value": 435263
                },
                {
                    "MARS": "single",
                    "year": 2019,
                    "value": 435263
                },
                {
                    "MARS": "widow",
                    "year": 2019,
                    "value": 435263
                },
                {
                    "MARS": "headhh",
                    "year": 2019,
                    "value": 435263
                },
                {
                    "MARS": "mseparate",
                    "year": 2019,
                    "value": 217631
                }
            ],
            "II_rt5": [
                {
                    "year": 2019,
                    "value": 0.33
                }
            ],
            "II_brk4_checkbox": [
                {
                    "value": true
                }
            ],
            "II_brk4": [
                {
                    "MARS": "mjoint",
                    "year": 2019,
                    "value": 243745
                },
                {
                    "MARS": "single",
                    "year": 2019,
                    "value": 200187
                },
                {
                    "MARS": "widow",
                    "year": 2019,
                    "value": 243745
                },
                {
                    "MARS": "headhh",
                    "year": 2019,
                    "value": 221966
                },
                {
                    "MARS": "mseparate",
                    "year": 2019,
                    "value": 121873
                }
            ],
            "II_rt4": [
                {
                    "year": 2019,
                    "value": 0.28
                }
            ],
            "II_brk3": [
                {
                    "MARS": "mjoint",
                    "year": 2019,
                    "value": 159920
                },
                {
                    "MARS": "single",
                    "year": 2019,
                    "value": 95994
                },
                {
                    "MARS": "widow",
                    "year": 2019,
                    "value": 159920
                },
                {
                    "MARS": "headhh",
                    "year": 2019,
                    "value": 137045
                },
                {
                    "MARS": "mseparate",
                    "year": 2019,
                    "value": 79960
                }
            ],
            "II_rt3": [
                {
                    "year": 2019,
                    "value": 0.25
                }
            ],
            "II_rt2": [
                {
                    "year": 2019,
                    "value": 0.15
                }
            ]
        }
    }
}
```

**Comment by andersonfrailey** [comment]
This looks like an error caused by the user toggling off  CPI indexing for the 6th income bracket.

The income thresholds in the fifth bracket are capped at whatever the income thresholds are in the sixth bracket. Similarly, the minimum income threshold in the sixth bracket is set to the threshold in the fifth bracket. By toggling off CPI for the sixth bracket, they've locked the income thresholds for the sixth bracket. However, the income threshold for the fifth bracket keep increasing according to inflation. In 2020 and beyond inflation causes the income threshold in the fifth bracket to exceed those in the sixth bracket, causing the error.

There's not much we can do here except maybe try and reformat the error message so that it's more clear to the user what happened.
